import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :simulacoes_visuais, SimulacoesVisuaisWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "tcUoMck2HJwgn3Rs3/10ofPo+Irx1rBX1oLt9MC4j6DW3AzspK/ZAonbm0vVjj+U",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:simulacoes_visuais, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:simulacoes_visuais, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :simulacoes_visuais, SimulacoesVisuaisWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/simulacoes_visuais_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :simulacoes_visuais, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Habilitar Repo + TelemetryWriter quando o banco estiver disponível (local ou Docker).
config :simulacoes_visuais, :tsdb_enabled, true

# Opcional: override do Batcher (artigo 07 §2.3). Default em config.exs: flush_interval_ms: 250, max_buffer_size: 100.
# config :simulacoes_visuais, :telemetry_batcher, [flush_interval_ms: 100, max_buffer_size: 80]

# Intervalo do Monte Carlo (ms). Com Nx no FBE_03, ticks mais frequentes são viáveis. Default 1500; em dev pode reduzir (ex.: 500).
config :simulacoes_visuais, :monte_carlo_interval_ms, 500

# Configure your database. Start PostgreSQL before mix ecto.create (e.g. from project root: docker compose up -d). See docs/docker.md.
# Docker: hostname "db" when app runs inside compose; local: "localhost".
config :simulacoes_visuais, SimulacoesVisuais.Repo,
  username: System.get_env("POSTGRES_USER", "postgres"),
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  hostname: System.get_env("POSTGRES_HOST", "localhost"),
  database: System.get_env("POSTGRES_DB", "simulacoes_visuais_dev"),
  port: String.to_integer(System.get_env("POSTGRES_PORT", "5432")),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# #region agent log
if System.get_env("MIX_ENV") != "test" do
  (fn ->
     log_path = "/home/sanonichan/projetos/tec0301_pon/.cursor/debug-3d1500.log"
     host = System.get_env("POSTGRES_HOST", "localhost")
     port_s = System.get_env("POSTGRES_PORT", "5432")
     db = System.get_env("POSTGRES_DB", "simulacoes_visuais_dev")
     mix_env = System.get_env("MIX_ENV", "dev")
     cwd = File.cwd!()

     line =
       "{\"sessionId\":\"3d1500\",\"hypothesisId\":\"B\",\"location\":\"config/dev.exs\",\"message\":\"Repo config at load\",\"data\":{\"host\":\"" <>
         host <>
         "\",\"port\":\"" <>
         port_s <>
         "\",\"database\":\"" <>
         db <>
         "\",\"mix_env\":\"" <>
         mix_env <>
         "\",\"cwd\":\"" <>
         String.replace(cwd, "\"", "\\\\\"") <>
         "\"},\"timestamp\":" <> Integer.to_string(System.system_time(:millisecond)) <> "}\n"

     File.mkdir_p!(Path.dirname(log_path))
     File.write!(log_path, line, [:append])
   end).()
end

# #endregion

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :simulacoes_visuais, SimulacoesVisuaisWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "mC629n1t077Ui+MXzQFNvboP/120F0FWWLr3fW4nh+GPLdUy2K/oQ/S+SCghg/PR",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:simulacoes_visuais, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:simulacoes_visuais, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :simulacoes_visuais, SimulacoesVisuaisWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/simulacoes_visuais_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :simulacoes_visuais, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
